<?php

/**
 * @file
 * AI Vector Database Provider for PostgreSQL.
 */

use Drupal\ai_search\Plugin\search_api\backend\SearchApiAiSearchBackend;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\search_api\IndexInterface;

/**
 * Implements hook_search_api_index_update().
 *
 * When the search API index is updated, check the fields are correctly
 * setup in Postgres.
 */
function ai_vdb_provider_postgres_search_api_index_update(IndexInterface $index) {
  $server = $index->getServerInstance();
  if (!($server->getBackend() instanceof SearchApiAiSearchBackend)) {
    return;
  }
  $backend_config = $server->getBackendConfig();
  if (!isset($backend_config['database'])) {
    return;
  }
  if ($backend_config['database'] !== 'postgres') {
    return;
  }
  $ai_vdb_provider_postgres = \Drupal::service('ai.vdb_provider')->createInstance('postgres');
  $connection = $ai_vdb_provider_postgres->getConnection($backend_config['database_settings']['database_name']);
  \Drupal::service('ai_vdb_provider_postgres.client')->updateFields(
    $index->getFields(),
    $backend_config['database_settings']['collection'],
    $connection,
  );
}

/**
 * Determines if a field is configured to accept multiple values.
 *
 * @param \Drupal\Core\Field\FieldItemListInterface $field
 *   The field to check.
 *
 * @return bool
 *   TRUE if the field cardinality is not 1, FALSE otherwise.
 */
function ai_vdb_provider_postgres_is_field_multiple($field) {
  if (!$field || !method_exists($field, 'getDataDefinition')) {
    return FALSE;
  }
  $data_def = $field->getDataDefinition();
  if (!method_exists($data_def, 'getFieldDefinition')) {
    return FALSE;
  }
  $field_definition = $data_def->getFieldDefinition();
  if ($field_definition instanceof BaseFieldDefinition) {
    $field_cardinality = $field_definition->getCardinality();
  }
  elseif (is_object($field_definition) && method_exists($field_definition, 'get')) {
    $storage = $field_definition->get('fieldStorage');
    $field_cardinality = $storage ? $storage->getCardinality() : 1;
  }
  else {
    $field_cardinality = 1;
  }
  if ($field_cardinality === 1) {
    return FALSE;
  }
  return TRUE;
}
